config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
mount Attachinary::Engine => "/attachinary"
root 'smoothies#index'
resources :smoothies, only: [:show, :new, :create] do
  resources :doses, only: [:new, :create, :destroy], shallow: true
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient, scope: :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/smoothie.rb
class Smoothie < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_attachment :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: :destroy
  before_action :set_smoothie, only: :create

  def create
    @dose = Dose.new(dose_params)
    @dose.smoothie = @smoothie
    if @dose.save
      redirect_to smoothy_path(@dose.smoothie)
    else
      render "smoothies/show"
    end
  end

  def destroy
    @dose.destroy
    # no need for app/views/doses/destroy.html.erb
    redirect_to smoothy_path(@dose.smoothie)
  end

  private

  def set_dose
    @dose = Dose.find(params[:id])
  end

  def set_smoothie
    @smoothie = Smoothie.find(params[:smoothie_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController
  before_action :set_smoothie, only: [:show, :edit, :update]

  def index
    @smoothies = Smoothie.all
  end

  def show
    @dose = Dose.new
  end


  def new
    @smoothie = Smoothie.new
  end

  def create
    @smoothie = Smoothie.new(smoothie_params)
    if @smoothie.save
      redirect_to smoothy_path(@smoothie)
    else
      render :new
    end
  end

  private

  def set_smoothie
    @smoothie = Smoothie.find(params[:id])
  end

  def smoothie_params
    params.require(:smoothie).permit(:name, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doses/_form.html.erb
<div class="container">
  <div class="form-dose">
    <%= simple_form_for [@smoothie, @dose] do |f| %>
      <%= f.association :ingredient, prompt: "Choisis un ingrédient", label: false %>
      <%= f.input :description, placeholder: "Quantité", label: false %>
      <%= f.submit 'Ajouter', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= content_for(:name) ? "Miss Smoothie | #{yield(:name)} " : "Miss Smoothie" %>
    </title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="wrapper">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-smoothie">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-smoothie-brand" do %>
    <%= image_tag "miss-smoothie-logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-smoothie-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Les Smoothies", root_path, class: "navbar-smoothie-item navbar-smoothie-link" %>
    <%= link_to "Ajouter mon Smoothie", new_smoothy_path(@smoothie), class: "navbar-smoothie-item navbar-smoothie-link" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-smoothie-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-smoothie-dropdown-menu">
        <%= link_to "Les Smoothies", root_path %>
        <%= link_to "Ajouter mon Smoothie", new_smoothy_path(@smoothie) %>
      </ul>
    </div>
  </div>
</div>

app/views/smoothies/_banner-index.html.erb
<div class="banner-index" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('images/banner.jpg')">
    <h1>Miss Smoothie</h1>
    <p>Vos recettes préférées de Smoothies !</p>
    <a class="btn btn-primary">Ajouter mon Smoothie</a>
  </div>
</div>

app/views/smoothies/_card.html.erb
<div class="container">
  <div class="text-center">Les Smoothies</div>
    <div class="row">
      <% @smoothies.each do |smoothie| %>
        <% if smoothie.picture? %>
          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="card">
              <div class="card-img text-center"><%= cl_image_tag smoothie.picture.path, width: 220, height: 200, crop: :fill %></div>
              <div class="card-name text-center"><%= link_to smoothie.name, smoothy_path(smoothie) %></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/smoothies/_navbar.html.erb
<div class="navbar-smoothie">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-smoothie-brand" do %>
    <%= image_tag "miss-smoothie-logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-smoothie-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Les Smoothies", root_path, class: "navbar-smoothie-item navbar-smoothie-link" %>
    <%= link_to "Ajouter mon Smoothie", new_smoothie_path(@smoothie), class: "navbar-smoothie-item navbar-smoothie-link" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-smoothie-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-smoothie-dropdown-menu">
        <%= link_to "Les Smoothies", root_path %>
        <%= link_to "Ajouter mon Smoothie", new_smoothie_path(@smoothie) %>
      </ul>
    </div>
  </div>
</div>

app/views/smoothies/index.html.erb
<%= render 'banner-index' %>

<%= render 'card' %>

app/views/smoothies/new.html.erb
<div class="container">
  <div class="form-smoothie">
    <%= simple_form_for @smoothie do |f| %>
      <%= f.input :name, placeholder: "Nom du Smoothie", label: false %>
      <%= f.input :picture, as: :attachinary, label: "Photo du Smoothie" %>
      <%= f.submit 'Ajouter', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/smoothies/show.html.erb
<div class="container">
  <% content_for :name do %>
  <%= @smoothie.name %>
  <% end %>
  <h2><%= @smoothie.name %></h2>
   <%= cl_image_tag @smoothie.picture.path, width: 200, height: 300, crop: :fill %>

  <p>Recette</p>
  <ul>
    <% @smoothie.doses.each do |dose| %>
      <% if dose.persisted? %>
        <li>
          <%= dose.description %> of <%= dose.ingredient.name %>
          <%= link_to "x", dose_path(dose), method: :delete %>
        </li>
      <% end %>
     <% end %>
  </ul>
  <p>Ajoutes un ingredient</p>
  <%= render 'doses/form' %>
</div>